api_config:
  base_url: "https://fakerapi.it/api/v2/"
  number_of_users: 100
  number_of_calls: 4
  batch_size: 2


schema: 
  columns:
    id: int64
    uuid: string
    firstname: string
    lastname: string
    username: string
    password: string
    email: string
    ip: string
    macAddress: string
    website: string
    image: string

target_configs: 
  pandas: 
    exclude_columns: []

  duckdb:
    exclude_columns:
      - id
    table_name: "faker_api_table"

gcs:
  row_size: 300
  bucket_name: "test-bucket"
  gcs_folder_name: "aidan-west"