version: '0.0.1'

services:
  ingestion-service:
    build: ./ingest
    volumes:
      - db_data:/data

  export-service:
    build: ./export
    volumes:
      - db_data:/data
    depends_on:
      ingestion-service:
        condition: service_completed_successfully

volumes:
  db_data: