api_config:
  base_url: "https://fakerapi.it/api/v2/"
  number_of_users: 100
  number_of_calls: 10
  batch_size: 4
  concurrency_limit: 2

duckdb:
  table_name: "faker_api_table"
  table_location: "/data/database.db"
  schema: 
    id: int64
    uuid: string
    firstname: string
    lastname: string
    username: string
    password: string
    email: string
    ip: string
    macAddress: string
    website: string
    image: string
 